spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:receipts
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  activemq:
    broker-url: tcp://localhost:61616
server:
  port: 8085
error:
  include-message: always
  include-binding-errors: always